name: vahanar_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.1.10
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1  # Ajout pour la navigation avancée
  pin_code_fields: ^8.0.1  # Ajout pour les champs de code PIN
  http: ^1.3.0 # Ajout pour les requêtes HTTP
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  flutter_animate: ^4.1.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  camera: ^0.11.0+1
  image: ^4.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  # Ajout pour la localisation (GPS)
  location: ^8.0.0
  # flutter_osm_plugin supprimé et remplacé par flutter_map
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_screenutil: ^5.9.3

  # Ajout pour les notifications
  flutter_local_notifications: ^19.0.0
  flutter_osm_plugin: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/vahanar1.png
    - assets/images/vahanful.png
    - assets/images/touareg.png
    - assets/images/profile_picture.png
    - assets/icons/facebook.png
    - assets/icons/insta.png
    - assets/icons/home.png
    - assets/icons/home_b.png
    - assets/icons/person.png
    - assets/icons/person_b.png
    - assets/icons/search.png
    - assets/icons/search_b.png
    - assets/icons/valide.png
    - assets/animations/earn.png
    - assets/animations/earn1.png
    - assets/icons/eclipse1.png
    - assets/icons/eclipse2.png
    - assets/icons/eclipse3.png
    - assets/icons/eclipse4.png
    - assets/icons/eclipse5.png
    - assets/icons/notif.png
    - assets/icons/sbl.png
    - assets/icons/suiv.png
    - assets/icons/disc.png
    - assets/icons/edit.png
    - assets/icons/de1.png
    - assets/icons/de2.png
    - assets/icons/de3.png
    - assets/icons/de4.png
    - assets/icons/mes.png
    - assets/icons/sms.png
    - assets/icons/gmail.png
    - assets/icons/wath.png
    - assets/icons/neloc.png
    - assets/icons/anloc.png





  # Fonts
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Light.ttf
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
