name: vahanar_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^10.1.2  # Ajout pour la navigation avancée
  pin_code_fields: ^8.0.1  # Ajout pour les champs de code PIN

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/vahanar.png
    - assets/images/grett.png
    - assets/icons/home.png
    - assets/icons/person.png
    - assets/icons/search.png
    - assets/icons/valide.png

  # Fonts
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Light.ttf
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
